### PR TITLE
DB: thousands of missing quest_poi & quest_poi_points

### LINKED ISSUE #43: [DB] QUEST_POI and QUEST_POI_POINTS
Majority of the quests are missing QUEST_POI and QUEST_POI_POINTS

### PR DESCRIPTION
**Pull request by Kitzunu**
Adds thousands of quest_poi's and quest_poi_points for a lot of quests.

Tested locally.

### CODE REVIEW

**Comment by Ovahlord** [comment]
may  I ask on which data this is based on?

**Comment by Kitzunu** [comment]
I apologise if it is not good q.q

But it is from another repack, but it is tested on Trinitycore's 4.3.4

**Comment by Ovahlord** [comment]
I just wanna know if the data is valid and if they come from 4.3.4 sniffs. Newer sniff data such as 6.x onwards for example have completely different POI's which are partially not compatible. But anyways, I will take a look at them. Thanks for your contribution.

**Comment by Ovahlord** [comment]
I took this in my own hands and were so free to use real sniffed data for it.
https://github.com/Ovahlord/TrinityCore/commit/938cdc5b0e362d1b78aad72c984a4e5cff1b262d
This should cover every single quest in database

**Pull request closed without merging**
